version: "2"
services:
  web:
    build: .
    container_name: "webAPI"
    environment:
      - ENV="docker"
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    container_name: "mongoDB"
    #volumes:
    #  - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"